# Home page
home_page:
  path: /
  controller: App\Controller\DefaultController::index

# Shopping page
shop_page:
  path: /{_locale}/shop
  controller: App\Controller\DefaultController::shop
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'

# Contact page
contact_page:
  path: /{_locale}/contact
  controller: App\Controller\DefaultController::contact
  defaults:
    _locale: 'en'
