# Home page
home_page:
  path: /{_locale}
  controller: App\Controller\DefaultController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'

# Shopping page
shop_page:
  path: /{_locale}/shop
  controller: App\Controller\DefaultController::shop
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'

# Contact page
contact_page:
  path: /{_locale}/contact
  controller: App\Controller\DefaultController::contact
  defaults:
    _locale: 'en'

# Search page
search_page:
  path: /{_locale}/shop/search/{search}
  controller: App\Controller\DefaultController::search
  defaults:
    _locale: 'en'
    search: ''