# Home page
home_page:
  path: /{_locale}
  controller: App\Controller\ShopController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'

######     SHOP ROUTES     #####
# index
shop_index:
  path: /{_locale}/shop
  controller: App\Controller\ShopController::shopIndex
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'

# category
shop_categ:
  path: /{_locale}/shop/{category}
  controller: App\Controller\ShopController::shopCateg
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'
    category: 0

######     CART ROUTES     #####
# index
# shop_index:
#   path: /{_locale}/cart/
#   controller: App\Controller\CartController::cartIndex
#   requirements:
#     _locale: '%app.supported_locales%'
#   defaults:
#     _locale: 'en'

# # TODO : add
# shop_index:
#   path: /{_locale}/cart/add/{idProduct}/{amount}
#   controller: App\Controller\CartController::cartAdd
#   requirements:
#     _locale: '%app.supported_locales%'
#   defaults:
#     _locale: 'en'

# # TODO : remove
# shop_index:
#   path: /{_locale}/cart/remove/{idProduct}/{amount}
#   controller: App\Controller\CartController::cartRemove
#   requirements:
#     _locale: '%app.supported_locales%'
#   defaults:
#     _locale: 'en'

# # TODO : delete
# shop_index:
#   path: /{_locale}/cart/delete/{idProduct}
#   controller: App\Controller\CartController::cartDelete
#   requirements:
#     _locale: '%app.supported_locales%'
#   defaults:
#     _locale: 'en'

# # TODO : empty
# shop_index:
#   path: /{_locale}/cart/empty
#   controller: App\Controller\CartController::cartEmpty
#   requirements:
#     _locale: '%app.supported_locales%'
#   defaults:
#     _locale: 'en'

# Search page
search_page:
  path: /{_locale}/shop/search/{search}
  controller: App\Controller\ShopController::search
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'
    search: ''

# Contact page
contact_page:
  path: /{_locale}/contact
  controller: App\Controller\ShopController::contact
  defaults:
    _locale: 'en'