# Home page
home_page:
  path: /{_locale}
  controller: App\Controller\ShopController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'

######     SHOP ROUTES     #####
# index
shop_index:
  path: /{_locale}/shop
  controller: App\Controller\ShopController::shopIndex
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'

# category
shop_categ:
  path: /{_locale}/shop/{category}
  controller: App\Controller\ShopController::shopCateg
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'
    category: 0

######     CART ROUTES     #####
# cart
cart_index:
  path: /{_locale}/cart/
  controller: App\Controller\CartController::cartIndex
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'

# add
cart_add:
  path: /{_locale}/cart/add/{idProduct}/{amount}
  controller: App\Controller\CartController::cartAdd
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    idProduct: 0
    amount: 0
    _locale: 'en'

# remove
cart_remove:
  path: /{_locale}/cart/remove/{idProduct}/{amount}
  controller: App\Controller\CartController::cartRemove
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'

# delete
cart_delete:
  path: /{_locale}/cart/delete/{idProduct}
  controller: App\Controller\CartController::cartDelete
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'

# empty
cart_empty:
  path: /{_locale}/cart/empty
  controller: App\Controller\CartController::cartEmpty
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'

# checkout (convert to command)
cart_checkout:
  path: /{_locale}/cart/{idUser}
  controller: App\Controller\CartController::cartCheckout
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    idUser: 0
    _locale: 'en'

######     GENERAL     #####
# Search page
search_page:
  path: /{_locale}/shop/search/{search}
  controller: App\Controller\ShopController::search
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'
    search: ''

# Contact page
contact_page:
  path: /{_locale}/contact
  controller: App\Controller\ShopController::contact
  defaults:
    _locale: 'en'
