# Home page
home_page:
  path: /{_locale}
  controller: App\Controller\DefaultController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'

# Shop home
shop_index:
  path: /{_locale}/shop
  controller: App\Controller\DefaultController::shopIndex
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'

# Shop categorie
shop_categ:
  path: /{_locale}/shop/{categorie}
  controller: App\Controller\DefaultController::shopCateg
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'en'
    categorie: 0

# Search page
search_page:
  path: /{_locale}/shop/search/{search}
  controller: App\Controller\DefaultController::search
  defaults:
    _locale: 'en'
    search: ''

# Contact page
contact_page:
  path: /{_locale}/contact
  controller: App\Controller\DefaultController::contact
  defaults:
    _locale: 'en'